"""Render a run spec as a Docker Compose file.

Compose rather than a long `docker run`, because the host is Docker Desktop
(ADR 0007) and a file that can be read, diffed and re-applied is worth more on
a machine somebody else also uses for gaming than a command in a shell history.

The generated file contains **no secrets**: a secret value is written back as
the `${PLACEHOLDER}` it came from, and `docker compose` substitutes it from
`deploy/.env` at run time. So the output is safe to commit and to read aloud.

Two things this deliberately does not emit:

**No healthcheck.** The manifest's liveness check is an A2S query, which would
mean putting a query client inside the game image. ADR 0006 consequence 5
separates the state reader from the thing being watched, and `hostlab status`
is that reader. Keeping it outside also keeps the game image thin and means a
health check that breaks against a game update cannot also break the container.

**No restart rate cap.** `restart: unless-stopped` retries with backoff but
neither caps nor reports. Compose's `restart_policy.max_attempts` only applies
under Swarm, which this is not, so writing it would look like a limit and be
nothing. `always-on-operation.md` wants a server that restarted eleven times
overnight treated as broken; that belongs to the status reader, which can see
`RestartCount`, and pretending compose does it would be worse than not doing it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import yaml

from hostlab.settings import redact

if TYPE_CHECKING:
    from collections.abc import Mapping

    from hostlab.render import RunSpec

HEADER = """\
# Generated by `hostlab compose`. Do not edit: regenerate it.
#
# Every value here is derived from titles/<title>.yaml (what the game is) and
# the instance file (what this server is). Editing it directly means the next
# regeneration silently reverts you, which is the same class of trap as putting
# configuration in start_server.sh.
#
# Secrets appear as ${PLACEHOLDER} and are substituted by docker compose from
# deploy/.env at run time, so this file is safe to commit.
"""


def compose_document(spec: RunSpec, placeholders: Mapping[str, str]) -> dict[str, Any]:
    service: dict[str, Any] = {
        "image": spec.image,
        "container_name": spec.container_name,
        "command": redact(spec.command, placeholders),
        # Every entry carries its protocol. Publishing 2456:2456 without /udp
        # publishes TCP and yields a server that looks correct and is
        # unreachable, which is ADR 0004 consequence 1.
        "ports": [port.published() for port in spec.ports],
        "volumes": [
            f"{volume.source}:{volume.target}" + (":ro" if volume.read_only else "")
            for volume in spec.volumes
        ],
        # Docker's defaults, SIGTERM after 10 seconds, are wrong on both counts
        # for this workload. Both values come from the manifest.
        "stop_signal": spec.stop_signal,
        "stop_grace_period": f"{spec.stop_grace_seconds}s",
        "restart": spec.restart,
    }

    # mem_limit and cpus rather than deploy.resources.limits: the latter is
    # honoured under Swarm, and this is a single machine that is also somebody's
    # gaming PC, where a limit that silently does nothing is the worst outcome.
    if spec.memory is not None:
        service["mem_limit"] = spec.memory
    if spec.cpus is not None:
        service["cpus"] = float(spec.cpus)

    document: dict[str, Any] = {"services": {spec.title_id: service}}

    named_volumes = {
        volume.source
        for volume in spec.volumes
        if "/" not in volume.source and "\\" not in volume.source
    }
    if named_volumes:
        document["volumes"] = dict.fromkeys(sorted(named_volumes))

    return document


def render_compose(spec: RunSpec, placeholders: Mapping[str, str]) -> str:
    body = yaml.safe_dump(
        compose_document(spec, placeholders), sort_keys=False, default_flow_style=False
    )
    return HEADER + "\n" + body
